### ISSUE TITLE
Slow typing performance when approx 45k characters used within editor

### ISSUE THREAD

**Issue by nialljawad96** [fleather-editor/fleather#244]
## Steps to Reproduce

1. Place 45000 characters into editor 
2. Type a sentence
3. Observe lag and delay

## Environment
- MacOS
- Flutter 3.16.4
- Fleather version 1.13.2

**Comment by amantoux** [comment]
@nialljawad96  thank you for pointing this out
Indeed performance on large pieces of text hasn't been tested yet.
Keeping this as reference as we will want to tackle this later

**Comment by Amir-P** [comment]
Hi @nialljawad96, we have a PR (#408) that might fix this issue. Would you be able to test it and get back to us? You can use it like following:
```
dependency_overrides:
  parchment:
    git:
      url: https://github.com/fleather-editor/fleather
      ref: perf/cache_offset_and_length_for_nodes
      path: packages/parchment
  fleather:
    git:
      url: https://github.com/fleather-editor/fleather
      ref: perf/cache_offset_and_length_for_nodes
      path: packages/fleather
```
