### ISSUE TITLE
HeadigStyle Positions

### ISSUE THREAD

**Issue by sanghyun8039** [fleather-editor/fleather#262]
Hi.

When i use Toolbar bottom Sticky,
![image](https://github.com/fleather-editor/fleather/assets/3152174/53b00b32-1d2e-4b49-9e0c-628ba95ceb9b)

i can't see HeadingStyle like  that
![스크린샷 2024-02-01 210843](https://github.com/fleather-editor/fleather/assets/3152174/f510bfa6-5a4f-405f-9e65-922a3f7a0e3e)

could you fix when i use bottom sticky toolbar to show heading style?

**Comment by Amir-P** [comment]
I think #329 fixes your problem. Could you please verify? @sanghyun8039 

```yaml
  fleather:
    git:
      url: https://github.com/fleather-editor/fleather
      ref: fix/toolbar_selector_positioning
      path: packages/fleather
```
