### ISSUE TITLE
Cursor Position / Text Overwritten on Android

### ISSUE THREAD

**Issue by Aggie85** [fleather-editor/fleather#288]
## Steps to Reproduce

Just compile and run the Fleather latest demo to an Android device and start typing ... you will see the cursor will immediately lose current position and previous typed text will be lost.

Just compile and run demo on Android.

## Environment
- Android 14
- Flutter version 3.19.2
- Fleather version 1.14.1

## Logs

```
```

**Comment by Amir-P** [comment]
Sorry for the delay. I've been busy. I wasn't able to reproduce the issue on Android emulator using the Fleather's example. Could you provide a video of the problem you're facing? @Aggie85

**Comment by Aggie85** [comment]
Howdy Amir-P,

I believe this is the same issue as #292 because all my Android phones are v14.

It works fine in all emulators ... just not phones.

All the best,

Aggie85

**Comment by Amir-P** [comment]
Thanks @Aggie85, I'll get back to you as soon as I can test it on an Android 14 device.

**Comment by Aggie85** [comment]
I appreciate your time & effort on Fleather!

If I can help, please let me know.

All the best,

Aggie85

**Comment by Amir-P** [comment]
Could you please test using the following? @Aggie85 

```yaml
fleather:
  git:
    url: https://github.com/fleather-editor/fleather
    ref: revert-229-fix/prevent_platform_selection_reach_last_newline
    path: packages/fleather
```
