### ISSUE TITLE
Link menu lacks bottom padding and clipping

### ISSUE THREAD

**Issue by maelchiotti** [fleather-editor/fleather#331]
## Steps to Reproduce

1. Insert a link
2. Open the link menu
3. Use the buttons

The button at the bottom doesn't take into account the device controls and displays under them, some padding should be added.

The button at the top isn't clipped and displays outside the bottom sheet (when selected).

https://github.com/fleather-editor/fleather/assets/44336112/46f79758-cbb3-47a1-8458-60536a3c587f

## Environment
OS: Android
Flutter version: 3.19.3
Fleather version: 1.14.4

**Comment by amantoux** [comment]
@maelchiotti 
Can you try on your device and let me know how if you still need the padding?

```
fleather:
    git:
      url: https://github.com/fleather-editor/fleather
      ref: fix/toolbar_selector_positioning
      path: packages/fleather
```
