### ISSUE TITLE
Can you add support for bold, strikethrough, underline, and italic Markdown syntax?

### ISSUE THREAD

**Issue by guoz2013** [fleather-editor/fleather#355]

**Comment by simonbengtsson** [comment]
I assume this is referring to supporting formatting text using markdown syntax (similar to Obsidian and Notion). For example that a word wrapped with _underscore_ would turn italics automatically. Text formatting such as bold, italics etc is already supported when encoding and decoding markdown.

**Comment by Amir-P** [comment]
Could you please give it a try and let me know if it works correctly? @simonbengtsson @guoz2013 

```yaml
  fleather:
    git:
      url: https://github.com/fleather-editor/fleather
      ref: feat/support_inline_markdown_shortcuts
      path: packages/fleather
```
