### ISSUE TITLE
Markdown encoder/decoder doesn't recognize "-" as start of unordered list item

### ISSUE THREAD

**Issue by adriank** [fleather-editor/fleather#442]
## Steps to Reproduce

``` dart
final doc = const ParchmentMarkdownCodec().decode('''
paragraph
- a
- b
- c
''');
```

The unordered list is not recognized. 

line 39 is:

```dart
static final _ulRegExp = RegExp(r'^( *)\* +(.*)');
```
and should be:

```dart
static final _ulRegExp = RegExp(r'^( *)[-\*\+] +(.*)');
```

There is also 
```dart
    ParchmentAttribute.ul: '* ',
```
which should probably be customizable, since it depends heavily on locale and context (for example, in books - is commonly used, not *).

Here is markdown recommendation: https://www.markdownguide.org/basic-syntax/#unordered-lists. Unordered list items can start with -, *, and +.

**Comment by Amir-P** [comment]
Thanks for reporting the issue! I believe #445 fixes it. Could you please give it a try and verify the fix? @adriank 

```yaml
  fleather:
    git:
      url: https://github.com/fleather-editor/fleather
      ref: fix/markdown_decoder_not_recognizing_all_ul_tokens
      path: packages/fleather
```
